# registry docker私有仓库
# mkdir -p /home/dockerdata/registry
version: '3.7'
services:
  registry:
    image: registry
    restart: unless-stopped
    container_name: registry
    environment:
        TZ: 'Asia/Shanghai'
    ports:
      - 5000:5000
    volumes:
      - /home/dockerdata/registry/data:/var/lib/registry
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
     - 84:80
    volumes:
      - ./certs/frontend.crt:/etc/apache2/server.crt:ro
      - ./certs/frontend.key:/etc/apache2/server.key:ro
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.100.15
      - ENV_DOCKER_REGISTRY_PORT=5000
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
