version: '3.7'
services:
  mysql-db:
    restart: always
    container_name: mysql        # 指定容器的名称
    image: mysql:8.0                   # 指定镜像和版本
    ports:
      - "3307:3306"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: zhuwenshen
    volumes:
      - "./data:/var/lib/mysql"           # 挂载数据目录
      - "./my.cnf:/etc/mysql/conf.d/my.cnf"      # 挂载配置文件目录
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"