apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-mysql-master
  labels:
    name: nacos-mysql-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nacos-mysql-master
  template:
    metadata:
      labels:
        name: nacos-mysql-master
    spec:
      containers:
      - name: master
        image: nacos/nacos-mysql-master:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-master-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "nacos_devtest"
        - name: MYSQL_USER
          value: "nacos"
        - name: MYSQL_PASSWORD
          value: "nacos"
        - name: MYSQL_REPLICATION_USER
          value: 'nacos_ru'
        - name: MYSQL_REPLICATION_PASSWORD
          value: 'nacos_ru'
      volumes:
      - name: mysql-master-data
        nfs:
          server: 192.168.0.249
          path: /root/nfs_root/nacos/nacos-mysql-master
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-mysql-master
  labels:
    name: nacos-mysql-master
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: nacos-mysql-master
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-mysql-slave
  labels:
    name: nacos-mysql-slave
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nacos-mysql-slave
  template:
    metadata:
      labels:
        name: nacos-mysql-slave
    spec:
      containers:
      - name: slave
        image: nacos/nacos-mysql-slave:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-slave-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_REPLICATION_USER
          value: 'nacos_ru'
        - name: MYSQL_REPLICATION_PASSWORD
          value: 'nacos_ru'
      volumes:
      - name: mysql-slave-data
        nfs:
          server: 192.168.0.249
          path: /root/nfs_root/nacos/nacos-mysql-slave
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-mysql-slave
  labels:
    name: nacos-mysql-slave
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: nacos-mysql-slave