apiVersion: v1
kind: Service
metadata:
  name: nacos-svc
  namespace: default
  labels: 
    name: nacos-svc
spec:
  type: NodePort
  ports:
  - port: 8848
    protocol: TCP
    targetPort: 8848
    name: http
    nodePort: 8848
  selector:
    app: nacos