# gitlab
# mkdir -p /home/dockerdata/nexus
version: '3.7'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:11.1'
      restart: unless-stopped
      hostname: '192.168.100.15'
      container_name: gitlab
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.100.15'
      ports:
        - '81:80'
        - '8443:443'
        - '2222:22'
      volumes:
        - /home/dockerdata/gitlab/config:/etc/gitlab
        - /home/dockerdata/gitlab/data:/var/opt/gitlab
        - /home/dockerdata/gitlab/logs:/var/log/gitlab
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
#默认用户名 root

---

# nexus maven私服
# mkdir -p /home/dockerdata/nexus
version: '3.7'
services: 
  nexus:     
    image: sonatype/nexus3
    restart: unless-stopped
    container_name: nexus
    environment:
        TZ: 'Asia/Shanghai'
    ports:
      - 82:8081
    volumes:
      - /home/dockerdata/nexus/nexus-data:/nexus-data
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"      
# http://ip:82/ 初始账号为admin
#chmod 777 /home/dockerdata/nexus/nexus-data

---

# registry docker私有仓库
# mkdir -p /home/dockerdata/registry
version: '3.7'
services:
  registry:
    image: registry
    restart: unless-stopped
    container_name: registry
    environment:
        TZ: 'Asia/Shanghai'
    ports:
      - 83:5000
    volumes:
      - /home/dockerdata/registry/data:/var/lib/registry
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
   
  frontend:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry_frontend
    ports:
      - 84:80
    volumes:
      - ./certs/frontend.crt:/etc/apache2/server.crt:ro
      - ./certs/frontend.key:/etc/apache2/server.key:ro
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.100.15
      - ENV_DOCKER_REGISTRY_PORT=83
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
        
---

