# mkdir -p /home/dockerdata/gitlab
version: '3.7'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:11.1'
      restart: unless-stopped
      hostname: '192.168.0.23'
      container_name: gitlab
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.0.23:81'
          gitlab_rails['gitlab_shell_ssh_port']=2222
          #unicorn['port']=81
          nginx['listen_port']=81
      ports:
        - '81:81'
        - '443:443'
        - '2222:22'
      volumes:
        - ./config:/etc/gitlab
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100M"
#        max-file: "10"
#默认用户名 root